version: '3'

services:
  db:
    image: postgres:9.6.10
    expose:
      - 5432
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
