version: '3'

services:
  db:
    image: postgres:latest
    environment:                                                              
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
      - POSTGRES_PORT=5432 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    volumes:
      - .:/code
    command: sh -c "urlwait $DATABASE_URL && ./manage.py migrate &&./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:                                                              
      - DATABASE_URL=postgres://postgres:password@db:5432/test_db
    depends_on:
      - db

volumes:
  postgres_data:
